-- Assistente financeiro v2: limite diário persistente e telemetria sem conteúdo financeiro.
-- Aplicar antes do deploy do novo /api/financial-assistant.

create table if not exists public.ai_assistant_daily_usage (
  user_id uuid not null references auth.users(id) on delete cascade,
  usage_date date not null,
  request_count integer not null default 0 check (request_count >= 0),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, usage_date)
);

create table if not exists public.ai_assistant_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  request_id uuid not null,
  status text not null check (status in ('success', 'error')),
  mode text not null,
  model text,
  tools text[] not null default '{}',
  record_count integer not null default 0 check (record_count >= 0),
  latency_ms integer not null default 0 check (latency_ms >= 0),
  error_code text,
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, request_id)
);

alter table public.ai_assistant_daily_usage enable row level security;
alter table public.ai_assistant_events enable row level security;

-- Sem policies: o navegador não lê nem escreve essas tabelas diretamente.
revoke all on public.ai_assistant_daily_usage from anon, authenticated;
revoke all on public.ai_assistant_events from anon, authenticated;

create or replace function public.consume_ai_assistant_quota(p_limit integer default 60)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  current_usage_date date := (timezone('America/Sao_Paulo', now()))::date;
  next_count integer;
begin
  if current_user_id is null then
    raise exception 'authentication required';
  end if;
  if p_limit < 1 or p_limit > 1000 then
    raise exception 'invalid quota limit';
  end if;

  insert into public.ai_assistant_daily_usage (user_id, usage_date, request_count, updated_at)
  values (current_user_id, current_usage_date, 1, timezone('utc', now()))
  on conflict (user_id, usage_date) do nothing
  returning request_count into next_count;

  if next_count is null then
    update public.ai_assistant_daily_usage
    set request_count = request_count + 1,
        updated_at = timezone('utc', now())
    where user_id = current_user_id
      and usage_date = current_usage_date
      and request_count < p_limit
    returning request_count into next_count;
  end if;

  if next_count is null then
    select request_count into next_count
    from public.ai_assistant_daily_usage
    where user_id = current_user_id and usage_date = current_usage_date;

    return jsonb_build_object(
      'allowed', false,
      'count', coalesce(next_count, p_limit),
      'limit', p_limit,
      'usage_date', current_usage_date
    );
  end if;

  return jsonb_build_object(
    'allowed', true,
    'count', next_count,
    'limit', p_limit,
    'remaining', greatest(0, p_limit - next_count),
    'usage_date', current_usage_date
  );
end;
$$;

create or replace function public.log_ai_assistant_event(
  p_request_id uuid,
  p_status text,
  p_mode text,
  p_model text,
  p_tools text[],
  p_record_count integer,
  p_latency_ms integer,
  p_error_code text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'authentication required';
  end if;
  if p_status not in ('success', 'error') then
    raise exception 'invalid event status';
  end if;

  insert into public.ai_assistant_events (
    user_id,
    request_id,
    status,
    mode,
    model,
    tools,
    record_count,
    latency_ms,
    error_code
  ) values (
    current_user_id,
    p_request_id,
    p_status,
    left(coalesce(p_mode, 'unknown'), 40),
    left(p_model, 120),
    coalesce(p_tools, '{}'),
    greatest(0, coalesce(p_record_count, 0)),
    greatest(0, coalesce(p_latency_ms, 0)),
    left(p_error_code, 80)
  )
  on conflict (user_id, request_id) do update set
    status = excluded.status,
    mode = excluded.mode,
    model = excluded.model,
    tools = excluded.tools,
    record_count = excluded.record_count,
    latency_ms = excluded.latency_ms,
    error_code = excluded.error_code;
end;
$$;

revoke all on function public.consume_ai_assistant_quota(integer) from public, anon;
revoke all on function public.log_ai_assistant_event(uuid, text, text, text, text[], integer, integer, text) from public, anon;
grant execute on function public.consume_ai_assistant_quota(integer) to authenticated;
grant execute on function public.log_ai_assistant_event(uuid, text, text, text, text[], integer, integer, text) to authenticated;

create index if not exists idx_ai_assistant_usage_date
  on public.ai_assistant_daily_usage(usage_date);

create index if not exists idx_ai_assistant_events_user_created
  on public.ai_assistant_events(user_id, created_at desc);

create index if not exists idx_ai_assistant_events_status_created
  on public.ai_assistant_events(status, created_at desc);
